/*   Copyright (c) 2015 Magnet Systems, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package com.magnet.mmx.protocol;

import com.google.gson.annotations.SerializedName;
import com.magnet.mmx.util.GsonData;
import com.magnet.mmx.util.JSONifiable;

import java.util.Date;

/**
 * @hide
 * The request and response of creating an application.
 */
public class AppCreate {
  /**
   * The application creation request payload.
   */
  public static class Request extends JSONifiable {
    @SerializedName("appName")
    private String mAppName;
    @SerializedName("serverUserId")
    private String mServerUserId; // if specified, server user will  be created
    @SerializedName("serverUserKey")
    private String mServerUserKey;  // required if server user ID is specified
    @SerializedName("authByServer")
    private boolean mAuthByAppServer;
    @SerializedName("guestSecret")
    private String mGuestSecret;
    @SerializedName("gcm")
    private GCM mGcm;
    @SerializedName("apns")
    private APNS mApns;
    @SerializedName("ownerEmail")
    private String ownerEmail;
    
    public String getAppName() {
			return mAppName;
		}

    /**
     * Set the application display name.
     * @param appName The application name.
     * @return This object.
     */
		public Request setAppName(String appName) {
			mAppName = appName;
			return this;
		}

    public String getServerUserId() {
      return mServerUserId;
    }

    /**
     * Specify the app server user ID.
     * @param serverUserId The app server user ID.
     * @return This object.
     */
    public Request setServerUserId(String serverUserId) {
      mServerUserId = serverUserId;
      return this;
    }

    public String getServerUserKey() {
      return mServerUserKey;
    }

    /**
     * Specify the app server user password.
     * @param serverKey The app server user password.
     * @return This object.
     */
    public Request setServerUserKey(String serverUserKey) {
      mServerUserKey = serverUserKey;
      return this;
    }

    public String getGuestSecret() {
      return mGuestSecret;
    }

    /**
     * Set the secret key for encryption purpose.  If it is not specified, it
     * will be generated by MMX server.
     * @param guestSecret The secret key, or null.
     * @return This object.
     */
    public Request setGuestSecret(String guestSecret) {
      mGuestSecret = guestSecret;
      return this;
    }

    public boolean isAuthByAppServer() {
      return mAuthByAppServer;
    }

    public Request setAuthByAppServer(boolean authByAppServer) {
      mAuthByAppServer = authByAppServer;
      return this;
    }

    public GCM getGcm() {
			return mGcm;
		}

		public Request setGcm(GCM gcm) {
			mGcm = gcm;
			return this;
		}

		public APNS getApns() {
			return mApns;
		}

		public Request setApns(APNS apns) {
			mApns = apns;
			return this;
		}

    public Request setOwnerEmail(String ownerEmail) {
      this.ownerEmail = ownerEmail;
      return this;
    }

    public String getOwnerEmail() {
      return ownerEmail;
    }

    public static Request fromJson(String json) {
      return GsonData.getGson().fromJson(json, Request.class);
    }
  }

  /**
   * The application creation response payload.
   */
  public static class Response extends JSONifiable {
    @SerializedName("appId")
    private String mAppId;
    @SerializedName("apiKey")
    private String mApiKey;
    @SerializedName("guestSecret")
    private String mGuestSecret;
    @SerializedName("creationDate")
    private Date mCreationDate;
    @SerializedName("modificationDate")
    private Date mModificationDate;
    
    public String getAppId() {
      return mAppId;
    }
    
    public Response setAppId(String appId) {
      this.mAppId = appId;
      return this;
    }
    
    public String getApiKey() {
      return mApiKey;
    }
    
    public Response setApiKey(String apiKey) {
      this.mApiKey = apiKey;
      return this;
    }

    public String getGuestSecret() {
      return mGuestSecret;
    }

    public Response setGuestSecret(String mGuestSecret) {
      this.mGuestSecret = mGuestSecret;
      return this;
    }
    
    public Date getCreationDate() {
      return mCreationDate;
    }
    
    public Response setCreationDate(Date creationDate) {
      mCreationDate = creationDate;
      return this;
    }
    
    public Date getModificationDate() {
      return mModificationDate;
    }
    
    public Response setModificationDate(Date modificationDate) {
      mModificationDate = modificationDate;
      return this;
    }

    public static Response fromJson(String json) {
      return GsonData.getGson().fromJson(json, Response.class);
    }
  }
}
